### ISSUE TITLE
Proposal to create a new repo and move some items out of the governance repo

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/governance#15]
**Overview**
I was thinking that it might be good to make a new repository specifically for "projects management".  There are several open issues and I created two project boards in governance about it, but they could live in their own repo, since it's turning into a place for tutorials and best practice examples and pretty soon its going to overwhelm using the governance repo. 

**Call to action:**
 Please review this PR and let me know if you agree or if you have questions.

**Details:** 

**Here are the Project boards I would move**
- Project Board Automation Example 1:
https://github.com/hackforla/governance/projects/3
- Project Board Automation Example 2:
https://github.com/hackforla/governance/projects/4

**Existing issues I would move to the new repo**
- 2018-04-24 Meeting: 
https://github.com/hackforla/governance/issues/1
- 2018-05-01-Meeting:
https://github.com/hackforla/governance/issues/2
- Project Frameworks from other Brigades:
https://github.com/hackforla/governance/issues/3
- Start the formation of a new project to create automation and add institutional value:
https://github.com/hackforla/governance/issues/8
- Gather and Review all info about Creating Processes for New Civic Projects in order return momentum to it: 
https://github.com/hackforla/governance/issues/12

**Additional assets that are in process of being written**
- Tutorials
  - How to write good issues for your project
  - How to build a github kanban board and organize your issues on it
- Lessons learned from HfLA project management Leads
- Best Practices checklist for projects with same issues to copy
  - Security reviews
  - Accessibility testing
  - cross platform browser compatibility

**Comment by thekaveman** [comment]
I'm not so sure the governance repo has outgrown itself yet, has it? There are only 26 files total, many of which (the images) could arguably be removed. I'm not convinced the `ndoch-2018` folder really belongs here at all. 

With #13 and some light touch cleanup of the existing files/structure, I feel like this repo can be much more than it currently is and still be useful.

I can be convinced otherwise, but I don't want to risk spreading everything so thin that navigating around repos becomes a challenge.

**Comment by ExperimentsInHonesty** [comment]
I think this is tightly tied to the permissions issue as well: https://github.com/hackforla/governance/issues/14.  When we sort the permission sout I think this will be a good example for dialog about do the permissions/teams have enough flexibility without creating additional repos.

**Comment by ExperimentsInHonesty** [comment]
We created a product management repo which was more accessible to projects.  The Community of Practice for Product is using the repo and contributing to it.
