### ISSUE TITLE
Enabling two-factor authentication on your github account

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/governance#20]
## Overiew

Hack for LA  requires two factor authentication (2FA) for Project Admins and it is recommended for all members.

**[Jump to Action Item: Setting up 2FA](#setting-up-2FA)**

## What is 2FA?

Two-factor authentication, or 2FA, is an extra layer of security used when logging into websites or apps. With 2FA, you have to log in with your username and password and provide another form of authentication that only you know or have access to.  

If you would like to read more information from github about 2FA: https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa

## Why setup 2FA now?

* We are in the process of establishing best practices on Hack for LA projects and in the HfLA organization's account (new setup of team structure, security, etc).
* There have been items in the news lately about hackers attempting to hold open source repositories for ransom: https://thenextweb.com/hardfork/2019/05/06/github-bitcoin-extortion-unsuccessful/ . Although these attempts seem to be unsuccessful its still a good reminder that we should use security best practices.

<h2 id="setting-up-2FA">------------</h2>
### Action Item - Setting up 2FA

[GitHub's guide to setting up 2FA](https://help.github.com/en/articles/configuring-two-factor-authentication). - takes about 2 min.

**Comment by ExperimentsInHonesty** [comment]
You might encounter a challenge using the git CLI after enabling 2-factor auth. Here are steps to get CLI auth working again:

1. Try pushing code from the CLI, if you get rejected unexpectedly it’s 2FA (if you enabled it)
2. [Clear your cached GH credentials]( https://stackoverflow.com/questions/11067818/how-do-you-reset-the-stored-credentials-in-git-credential-osxkeychain)
3. [Create a token at GH.com, which you’ll use as your CLI password](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)

Thanks to @wesrowe for providing the instructions

**Comment by thekaveman** [comment]
It should also be noted that if you clone via the `ssh` URL for a repo e.g. 

    git@github.com:hackforla/governance.git

instead of the `https` URL e.g.

    https://github.com/hackforla/governance.git

then you probably won't run in to any issues after enabling 2FA, as you already use an SSH key.

Read more about [connecting to GitHub with SSH](https://help.github.com/en/articles/connecting-to-github-with-ssh).

**Comment by ExperimentsInHonesty** [comment]
Added 2FA guide to the website.https://www.hackforla.org/guide-pages/2FA
