### ISSUE TITLE
Create a new repository and related teams for shared-housing

### ISSUE THREAD

**Issue by abregorivas** [hackforla/governance#26]
Please add @abregorivas, @owenjoseph (Owen) and @awadethomas (Arron) to the repo as admins.

**Comment by ExperimentsInHonesty** [comment]
The repository has been created: 
https://github.com/hackforla/shared-housing

The teams have been setup:
- https://github.com/orgs/hackforla/teams/shared-housing
- https://github.com/orgs/hackforla/teams/shared-housing-managers
- https://github.com/orgs/hackforla/teams/shared-housing-admins

The following members have been added: 
- Marie (Manager)
- Roland (Admin)
- Aaron (Admin)
- Owen (Admin)
- Philippe
- Ryan (Member)

If more members need to be added, they can be added by Admins.
