### ISSUE TITLE
Create Wiki for COP

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/governance#52]
### Overview
We need to create a Wiki for COP repo so people can better understand how to participate in COPs and the value that COPs bring.

### Action Items
- [x] Research COP definitions
- [ ] Write the Wiki for COP repo and includin
   - [ ] How do you join a community?
   - [ ] What documents should you read?
   - [ ] How do you participate?

### Resources/Instructions
[Community of Practice README.md](https://github.com/hackforla/communities-of-practice/blob/main/README.md)
[Update README.md on the community of practice repo issue on the repo](https://github.com/hackforla/communities-of-practice/issues)

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong can you look at the readme and determine if we really NEED a wiki?  

https://github.com/hackforla/communities-of-practice/blob/main/README.md

**Comment by Olivia-Chiong** [comment]
Wiki has been resolved by putting information on the readme. Issue closed.
