### ISSUE TITLE
Hack For LA website must launch redesign by summit

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/governance#9]
**Who's Here?**
* Bonnie
* Nina

**What did we do?**

Discussed the need for the HackForLA website to get completed before the summit.

**What are the current challenges**

- Lack of time for Tech Team lead to review and comment on Pull Requests.
- New format, means Tech lead is creating rules and structure as we go, which involves some rework.
- Coding teams’s lack of familiarity with the gh-pages/Jekyll/Liquid standards (Tech Lead is familiar).
- Coding team's relative inexperience.  Requires mentorship from Tech Lead.

**The tasks that remain to get the website launched**

1. Kegan - to Approve or Comment on the following open pull requests - all changes Kegan have requested have been made by their respective authors:
    * Add the new criminal-sententancing project to OLD hfla site 
 	#63 opened 8 days ago by ExperimentsInHonesty 
    * Add the new criminal-sententancing project to new hfla site
	#62 opened 8 days ago by ExperimentsInHonesty 
    * Added Hack Nights Section to Events
	#60 opened 11 days ago by DDRosario 
    * Add About/contact section
	#54 opened 23 days ago by abregorivas • Changes requested  
    * Add Hero Section
	#51 opened 23 days ago by abregorivas • Changes requested  
    * Header, Nav & Footer added & hooked to Default.html
	#48 opened 24 days ago by abregorivas • Changes requested  
2. Bonnie - to finish assembling the Calendar code that Drew, Roland and Bonnie worked on Tuesday 4/16.
    1. Summit pull request.  
    2. Review pull request with Kegan, because it’s not currently working with the API and we can’t quite figure out why.  
3. Unassigned - Check code for accessibility WCAG 2 Checklist (https://webaim.org/standards/wcag/checklist).
    1. Unassigned - Document what changes need to be made and submit as issue on Github.
    2. Kegan -  Review document to define any rules/exception for the proposed changes.
    3. Assign team members to make changes.
    4. Team member submit pull requests.
    5. Kegan reviews pull requests and either responds with requested changes or approves.
        1. If changes requested, team member makes changes and updates pull request.
        2. Repeat #5 until pull request approved.
4. Unassigned - add Open Graph Markup tags to header (https://developers.facebook.com/docs/sharing/webmasters#markup).  This is to ensure that when the website is shared on slack, facebook, twitter, etc.  It automatically displays with an image and Title instead of just the URL.
5. Unassigned - add favicon back into the header.
    1. Submit pull request
    2. Kegan reviews pull requests and either responds with requested changes or approves.
        1. If changes requested, team member makes changes and updates pull request.
        2. Repeat second step until pull request approved.

**Comment by abregorivas** [comment]
I would add two points here.
1. We should establish a timeline to ensure task are handled timely and the site is live before the summit.
2. I suggest we merge all the pull requests to have a working copy of the "completed" work. This would allow for the following;
 - Everyone would be able to see the full state of the site.
-  A full review of open issues or possible refactors can begin
-  Helps catch early issues
- Can better distribute open tasks with current volunteers

**Comment by ExperimentsInHonesty** [comment]
Document additions could include: 
Current working schedule
List of team members
Availability of team members to current working schedule (some people available on Mondays and some on Tuesdays), and additional time they may be available (such as if we do an all day push).

Resources available to help team finish site:
Space options: 
Bonnie's house in Playa Vista (can accommodate 8 people working).
LACI DTLA we can book a room.
Potential other locations
Bonnie's Zoom meeting account so we can meet remotely.

**Comment by ExperimentsInHonesty** [comment]
All the related open PRs have been approved.  New issues from the task list above have been added directly to the hfla website repository.

**Comment by thekaveman** [comment]
I'm closing since we made the cut over, and did it before Summit!
